### PR TITLE
Created thee.it CRUD Rest api

### PR DESCRIPTION
**Pull request by cmshaki**

### CODE REVIEW

**Comment by ClydeDz** [comment]
Hey @cmshaki, did you create a PR to the wrong repository by any chance? The code looks very specific to your application.

**Comment by cmshaki** [comment]
Hey sorry didn't mean to push to your repo

**Comment by cmshaki** [comment]
But let us know if you are interested in the code or prefer we don't keep a fork of your repo, however am sure there are some elements that could further your cause regards

**Comment by ClydeDz** [comment]
No worries. Thanks for clarifying and closing the PR. Feel free to continue work on your fork of this repo. 

The code in this repo is really meant to be demo-only and best understood when read with [my Medium article](https://bit.ly/cdz858) on this topic. So, I'll be happy to accept a PR if there's a bug/change to the core demo files but not really looking for additional features. Hope this helps!

**Pull request closed without merging**
